#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "utils.h"
#include "operation.h"
#include "stringBuffer.h"

#define OPERATION_MISSING '?'

int main() {

    // initialize default values
    char * line = calloc(MAX_CHAR, sizeof( char ));
    char * value = NULL;
    // string of operators
    char * operators_combinations = NULL;
    // 'operators' is the buffer that will get both numbers from input
    int * operators = (int *) malloc(2 * sizeof(int));

    // Operation struct array
    Operation* operations = NULL;

    // initialize counter variables
    int i = 0, valid_chars_counter = 0, id = 0, op_count = 0, result;

    // get line characters from stdin
	scanf("%[^\n]s", line);

    // get first line as char* from file
    if ( strlen(line) ){

        // first principal loop
        // get string one by one until get \n
        while( NULL != (value = strtok(NULL == value ? line : NULL, " \n")) ){

            if( EMPTY_CHAR  == *value ) {
                // while we get EMPTY_CHAR, set i += strlen to jump
                i += strlen( value ) + 1;
                continue;
            }

            if( OPERATION_MISSING  == *value ) {
                // when do we get '?' operator:
                // 1 - we retrieve the string that strtok messed up
                recoverString(line);
                // 2 - so we create a new Operation struct (a node in the tree)
                operations = newOperation( operations, op_count, &id );
                // 3 - set the new operation as a new tree root
                setNewOperationAsTreeNode( operators, operations, op_count );
                // 4 - modify the input string with 'G' and 'E' chars
                setStringBufferWithCustomChars(&i, line);

                // increment operation counter
                op_count++;
                // important: setting value = NULL will make strtok keep on his actual buffer
                value = NULL;
            } else {
                // here, we got a valid character( 'G' or a number )
                // if is a 'G', set operators(j mod 2) with -2 or with the number
                // with mod we can get last two
                operators[valid_chars_counter % 2] = * value == GROUP_CHAR ? GROUP_VALUE : atoi( value );
                // set the jumper with strlen
                i += strlen( value ) + 1;
                // increment valid char count
                valid_chars_counter++;
            }
        }

        // get result from stdin
		scanf("%d", &result);

        // alloc memory to string of operators
        operators_combinations = (char *) calloc( (size_t) (op_count + 1), sizeof( char ) );

        // second principal loop
        // for i = 0 to 2^(op_count-1)
        for( i = 0; i < (0x2 << (op_count - 1)); i++ ){
            // we will use the i counter to get the operators
            convertNumberToOperator( i, operators_combinations, op_count );
            // pass to recursion the tree, operations counter and string of combinations
            if( result == calcResultRecursion( operations, op_count-1, operators_combinations ) ){
                // if recursion result on a number == result from stdin
                // print the string of operations generated by i
                printf( "%s\n", operators_combinations );
            }
        }
        if( operators_combinations ) free( operators_combinations );
    }

    // mark allocated memory as thrash
	if( operations ) free( operations );
    if( operators ) free( operators );
    if( line ) free( line );

    return EXIT_SUCCESS;
}